apiVersion: 1

datasources:
  - name: Finance PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: finance_db
    user: finance
    secureJsonData:
      password: ${GF_DATABASE_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1200
